import LegalPage from '@/components/legal/LegalPage';

export const metadata = { title: 'Privacy — Odyssey' };

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Notice" description="What Odyssey processes today, where it stays, and which providers may receive it.">
      <section><h2>Information processed</h2><p>Odyssey may process search terms, trail preferences, theme and accessibility settings, saved trail records, approximate or precise device location, and GPS points recorded during an active hike. If you sign in, the authentication provider may return basic account information such as name, email address, profile image, and an account identifier.</p></section>
      <section><h2>Local device storage</h2><p>Saved trail facts, active hike records, GPS points, search history, display preferences, and short-lived verified search results may be stored in localStorage, sessionStorage, cookies, IndexedDB, or the service worker cache on your device. Interactive basemap resources may use ordinary browser and provider caching but are not intentionally packaged for offline use. Browser controls or clearing site data can remove local records.</p></section>
      <section><h2>Server processing</h2><p>Account preferences may be stored in Odyssey’s database when an authenticated user chooses to save them. Anonymous hike routes and community reviews are not accepted by the current production routes. Server logs may temporarily contain ordinary request and error metadata needed for security and reliability.</p></section>
      <section><h2>Third parties</h2><ul><li>Google may process sign-in information when Google authentication is enabled. Opening an external Google Maps directions link sends the selected coordinates and normal network information to Google.</li><li>National Park Service APIs provide official park alerts and boundary data.</li><li>Stadia Maps provides the interactive basemap and receives ordinary network metadata such as IP address, user agent, origin, and referrer. OpenStreetMap infrastructure may receive ordinary network metadata when identified route relation geometry is requested.</li><li>Anthropic may receive the selected trail facts, a question, and conversation context only when the optional Trail Guide or refinement feature is used and configured.</li></ul></section>
      <section><h2>Advertising, sale, and tracking signals</h2><p>Odyssey does not currently sell personal information, share it for cross-context behavioral advertising, or integrate advertising or third-party analytics. Because Odyssey does not currently perform cross-site behavioral tracking, browser Do Not Track or Global Privacy Control signals do not change the app’s behavior. Feature providers listed above may receive requests and ordinary network metadata needed to provide their services under their own privacy terms.</p></section>
      <section><h2>Purpose, retention, and choices</h2><p>Information is used to provide search, preferences, saved trails, local tracking, optional assistance, security, and troubleshooting. Local information remains until you remove it or clear browser data. Account preferences remain until deleted or the service is retired. Do not submit sensitive personal information in free-text search or AI fields.</p></section>
      <section><h2>Access, correction, and deletion</h2><p>You can remove local records by using available in-app controls or clearing this site’s browser data. To request access to, correction of, or deletion of server-side account information, use the contact method on the operator’s <a href="https://github.com/Shilpi924">GitHub profile</a> to request a private communication channel. Do not post account details, location history, passwords, or other personal information in a public issue. Identity verification may be required before fulfilling a request.</p></section>
      <section><h2>Children</h2><p>Odyssey is a general-audience service and is not directed to children under 13. Children under 13 should not create an account or submit personal information. A parent or guardian who believes a child has provided personal information should contact the operator.</p></section>
      <section><h2>Changes to this notice</h2><p>The effective date appears above. Material changes will be identified by updating that date and posting a prominent notice in the service. Odyssey will request additional permission before applying a materially different use to previously collected precise location or account information when applicable law requires it. This notice must be reviewed again before collecting community content, payments, analytics, advertising identifiers, or cloud GPS histories.</p></section>
    </LegalPage>
  );
}
