import LegalPage from '@/components/legal/LegalPage';

export const metadata = { title: 'Data Sources — Odyssey' };

export default function DataSourcesPage() {
  return (
    <LegalPage title="Data Sources & Attribution" description="Where trail facts, conditions, geometry, and maps come from—and what Odyssey does not infer.">
      <section><h2>National Park Service</h2><p>Yosemite trail facts, access notes, park alerts, and boundaries are sourced from the <a href="https://www.nps.gov/subjects/digital/nps-data-api.htm">U.S. National Park Service</a> and linked official NPS pages. U.S. federal government works are generally not copyrighted in the United States, but NPS pages can contain third-party material, trademarks, or other restrictions. Source: National Park Service. Always verify the current official page.</p></section>
      <section><h2>California State Parks</h2><p>Mount Diablo trail identities, selected route facts, accessibility details, trail-use designations, and route lines come from linked <a href="https://www.parks.ca.gov/?page_id=517">California State Parks</a> pages and its official ArcGIS trail layer. California State Parks source materials may be copyrighted. Odyssey uses individual facts and provider-supplied geometry with attribution and does not reproduce the park brochure or map artwork.</p></section>
      <section><h2>OpenStreetMap</h2><p>Community trail discovery, available trail relation geometry, and underlying map data are © OpenStreetMap contributors and offered under the <a href="https://www.openstreetmap.org/copyright">Open Database License (ODbL)</a>. Outside Odyssey’s verified catalog, search may return named hiking routes and named mapped paths near the requested area. Community records can be incomplete or outdated, so Odyssey links each result to its OSM record and leaves unsupported difficulty, distance, rating, access, and elevation facts unknown.</p></section>
      <section><h2>Interactive basemap</h2><p>The interactive map uses Stadia Maps’ paired Alidade Smooth light and dark vector styles, with attribution to Stadia Maps, OpenMapTiles, and OpenStreetMap. The public tile.openstreetmap.org endpoint is not used by the current map configuration, and Odyssey does not offer basemap prefetching or offline downloads. Local development and evaluation may use Stadia’s free tier; production release requires a commercial Stadia plan and production-domain authentication.</p></section>
      <section><h2>Odyssey classifications</h2><p>Odyssey may add first-party aliases, entity links, completeness scoring, or normalized difficulty labels. The catalog records the method and source. Ratings, review counts, crowd estimates, air quality, pollen, closures, and access status are not manufactured when unavailable. Route geometry is displayed only when a catalog record identifies an official or reviewed geometry source.</p></section>
      <section><h2>Current exclusions</h2><p>Google Places, Google Geocoding, Google Elevation, CARTO basemaps, Mapzen terrain, and Open-Meteo weather are not used in the current displayed trail-search flow. AllTrails content is not scraped, copied, or used as a result provider.</p></section>
    </LegalPage>
  );
}
